#!/bin/bash

# Install dependencies
echo "Install dependencies..."
xbps-install -Syu rofi bspwm sxhkd feh setxkbmap xsetroot xclip scrot kitty

# move wallpaper
echo "Move wallpaper to Pictures"
mv -v wallpaper.jpg $HOME/Pictures/

# Install config
echo "Install config"
mkdir -p $HOME/.config
mv -fv cfg/* $HOME/.config/

# Install fonts
echo "Install fonts"
mkdir -p $HOME/.fonts
mv -fv fonts/* $HOME/.fonts
fc-cache -fv

# Setup rofi theme
echo "Setup rofi theme"
mkdir -p $HOME/.local/share/rofi/themes
mv rofi-themes/tokyonight $HOME/.local/share/rofi/themes/
rm -r rofi-themes


