#! /bin/sh

#------------------ Autostart Apps ------------------#

# Fix cursor
xsetroot -cursor_name left_ptr &

# Switch keyboard layouts
setxkbmap -option grp:alt_shift_toggle us,th &

# Autostart Apps
pgrep -x sxhkd > /dev/null || sxhkd &
feh --bg-scale $HOME/Pictures/wallpaper.png &
$HOME/.config/polybar/launch.sh &
picom --experimental-backend &


#------------------ Window rules --------------------#

bspc monitor -d 1 2 3 4 5 6

bspc rule -a discord                     desktop=3 follow=on
#bspc rule -a Alacritty                   state=floating follow=on
bspc rule -a Steam                       desktop=4 follow=on
#bspc rule -a Thunar                      state=floating follow=on
#bspc rule -a feh                         state=floating


#------------------ Bspwm config ---------------------#

bspc config border_width         2
bspc config window_gap           4

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true


#--------------------- Other -------------------------#
