#! /bin/sh

#------------------ Autostart Apps ------------------#

# Fix cursor
xsetroot -cursor_name left_ptr &

# Switch keyboard layouts
setxkbmap -option grp:alt_shift_toggle us,th &

# Autostart Apps
pgrep -x sxhkd > /dev/null || sxhkd &
#feh --bg-scale $HOME/Pictures/siesta.jpg &
feh --bg-scale /home/watson/Pictures/Minimalist\ wallpapers/4.png &
$HOME/.config/polybar/launch.sh &
picom --experimental-backend &


#------------------ Window rules --------------------#

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc rule -a firefox                     desktop=1 follow=on
bspc rule -a Alacritty                   desktop=2 follow=on
bspc rule -a discord                     desktop=3 follow=on
bspc rule -a Steam                       desktop=4 follow=on
bspc rule -a Code                        desktop=5 follow=on
bspc rule -a Spotify			               desktop=6 follow=on
#bspc rule -a Thunar                      state=floating follow=on
#bspc rule -a feh                         state=floating


#------------------ Bspwm config ---------------------#

bspc config border_width         0
bspc config window_gap           4

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true


#--------------------- Other -------------------------#
