#! /bin/sh

#------------------ Autostart Apps ------------------#

# Fix cursor
xsetroot -cursor_name left_ptr &

# Switch keyboard layouts
# setxkbmap -option grp:alt_shift_toggle us,th &

# Autostart Apps
pgrep -x sxhkd > /dev/null || sxhkd &
feh --bg-scale /home/watson/Pictures/wallpaper.jpg &
$HOME/.config/polybar/launch.sh &


#------------------ Window rules --------------------#

bspc monitor -d 1 2 3 4 5 6 7 8 9

#bspc rule -a firefox                     desktop=1 follow=on
#bspc rule -a Alacritty                   desktop=2 follow=on
#bspc rule -a discord                     desktop=3 follow=on
#bspc rule -a Steam                       desktop=4 follow=on
#bspc rule -a Code                        desktop=5 follow=on
#bspc rule -a Spotify			                desktop=6 follow=on
#bspc rule -a Thunar                      state=floating follow=on
#bspc rule -a feh                         state=floating


#------------------ Bspwm config ---------------------#

bspc config border_width         1
bspc config window_gap           4

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config active_border_color   \#1a1a1a
bspc config normal_border_color   \#1a1a1a
bspc config urgent_border_color   \#1a1a1a
bspc config focuesd_border_color  \#1a1a1a
bspc config presel_border_color   \#1a1a1a

#--------------------- Other -------------------------#
