#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
feh --bg-scale ~/Pictures/wallpaper-3.jpg &
$HOME/.config/polybar/launch.sh &
setxkbmap -option grp:alt_shift_toggle us,th &
picom &
$HOME/.config/conky/Regulus/start.sh &
bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         3
bspc config window_gap          10

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config normal_border_color "#2A547E"
bspc config active_border_color "#366BA1"
bspc config focused_border_color "#4482C1"
bspc config presel_feedback_color "#6699CC"

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

