#! /bin/sh

# Startup
pgrep -x sxhkd > /dev/null || sxhkd &
xfce4-power-manager &
picom -b &
feh --bg-scale ~/Pictures/Wallpaper/wallpaper.png &
polybar main &
#$HOME/.config/polybar/launch,sh

# Workspace
bspc monitor -d 1 2 3 4 5 6 7 8 9 10

# Other stuff
bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.60
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating
bspc rule -a Zathura state=tiled
bspc rule -a Transmission desktop='^10' follow=on
bspc rule -a transmission-gtk desktop='^10' follow=on
